package bo.net.tigo.model;

/**
 * Created by aralco on 11/11/14.
 */
public enum Status {
    SCHEDULED, STARTED, COMPLETED_PHASE1_OK, COMPLETED_PHASE1_WITH_ERRORS, STARTED_PHASE2, COMPLETED_OK, COMPLETED_WITH_ERRORS, RE_SCHEDULED, CANCELLED
}
