select * from ILN_JOB;
select * from ILN_TASK;
select * from ILN_ORDERREQUEST;
drop table ILN_ORDERREQUEST;
drop table ILN_TASKREQUEST;

INSERT INTO "IMPORTLUCKY"."ILN_USER" (ILN_USER_ID, ILN_USER_NAME, ILN_USER_ENABLED, ILN_USER_USERNAME, ILN_USER_PASSWORD, ILN_USER_ROLE) VALUES ('1', 'SYSPORTALUSER', '1', 'sysportal', 'Sysp0rt4l', 'ROLE_USER');
INSERT INTO "IMPORTLUCKY"."ILN_USER" (ILN_USER_ID, ILN_USER_NAME, ILN_USER_ENABLED, ILN_USER_USERNAME, ILN_USER_PASSWORD, ILN_USER_ROLE) VALUES ('2', 'ADMINUSER', '1' , 'admin', 'admin', 'ROLE_ADMIN');

