//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.22 at 10:07:45 AM BOT 
//


package bo.net.tigo.wsdl;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the bo.net.tigo.wsdl package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _EnviarMail_QNAME = new QName("http://sms.ws.tigo.com/", "enviarMail");
    private final static QName _EnviarMailResponse_QNAME = new QName("http://sms.ws.tigo.com/", "enviarMailResponse");
    private final static QName _EnviarSms_QNAME = new QName("http://sms.ws.tigo.com/", "enviarSms");
    private final static QName _EnviarSmsResponse_QNAME = new QName("http://sms.ws.tigo.com/", "enviarSmsResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: bo.net.tigo.wsdl
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link EnviarMail }
     * 
     */
    public EnviarMail createEnviarMail() {
        return new EnviarMail();
    }

    /**
     * Create an instance of {@link EnviarMailResponse }
     * 
     */
    public EnviarMailResponse createEnviarMailResponse() {
        return new EnviarMailResponse();
    }

    /**
     * Create an instance of {@link EnviarSms }
     * 
     */
    public EnviarSms createEnviarSms() {
        return new EnviarSms();
    }

    /**
     * Create an instance of {@link EnviarSmsResponse }
     * 
     */
    public EnviarSmsResponse createEnviarSmsResponse() {
        return new EnviarSmsResponse();
    }

    /**
     * Create an instance of {@link RespuestaSMS }
     * 
     */
    public RespuestaSMS createRespuestaSMS() {
        return new RespuestaSMS();
    }

    /**
     * Create an instance of {@link GeneralResponse }
     * 
     */
    public GeneralResponse createGeneralResponse() {
        return new GeneralResponse();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EnviarMail }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://sms.ws.tigo.com/", name = "enviarMail")
    public JAXBElement<EnviarMail> createEnviarMail(EnviarMail value) {
        return new JAXBElement<EnviarMail>(_EnviarMail_QNAME, EnviarMail.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EnviarMailResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://sms.ws.tigo.com/", name = "enviarMailResponse")
    public JAXBElement<EnviarMailResponse> createEnviarMailResponse(EnviarMailResponse value) {
        return new JAXBElement<EnviarMailResponse>(_EnviarMailResponse_QNAME, EnviarMailResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EnviarSms }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://sms.ws.tigo.com/", name = "enviarSms")
    public JAXBElement<EnviarSms> createEnviarSms(EnviarSms value) {
        return new JAXBElement<EnviarSms>(_EnviarSms_QNAME, EnviarSms.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EnviarSmsResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://sms.ws.tigo.com/", name = "enviarSmsResponse")
    public JAXBElement<EnviarSmsResponse> createEnviarSmsResponse(EnviarSmsResponse value) {
        return new JAXBElement<EnviarSmsResponse>(_EnviarSmsResponse_QNAME, EnviarSmsResponse.class, null, value);
    }

}
